# Generated by Django 2.0.5 on 2019-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='isComing',
            field=models.BooleanField(default=True),
        ),
    ]
