# Generated by Django 2.0.6 on 2019-05-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_guest_needtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='transferConfirm',
            field=models.BooleanField(default=False),
        ),
    ]
