# Generated by Django 2.0.6 on 2019-05-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_guest_transferconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
