# Generated by Django 2.0.6 on 2019-05-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_guest_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
