# Generated by Django 2.0.6 on 2019-06-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_guest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garnish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_garnish', to='invitation.Dishes')),
                ('mainDish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_mainDish', to='invitation.Dishes')),
                ('salat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_salat', to='invitation.Dishes')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='alcohol',
            field=models.ManyToManyField(blank=True, null=True, to='invitation.Dishes'),
        ),
        migrations.AddField(
            model_name='guest',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitation.Menu'),
        ),
    ]
