# Generated by Django 2.0.6 on 2019-06-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0008_auto_20190601_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='salat',
        ),
        migrations.AddField(
            model_name='dishes',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menu',
            name='salad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_salat', to='invitation.Dishes'),
        ),
    ]
