# Generated by Django 2.0.6 on 2019-06-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_auto_20190601_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='alcohol',
            field=models.ManyToManyField(blank=True, null=True, to='invitation.Alcohol'),
        ),
    ]
