# Generated by Django 2.0.6 on 2019-06-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0010_auto_20190602_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guestsIsVisible',
            field=models.BooleanField(default=True),
        ),
    ]
