# Generated by Django 2.0.6 on 2019-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0011_guest_guestsisvisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
