# Generated by Django 2.0.6 on 2019-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0012_guest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
