# Generated by Django 2.0.6 on 2019-06-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0014_guest_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitation.Menu'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='middleName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
