# Generated by Django 2.2.1 on 2019-07-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0017_auto_20190606_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postUrl', models.CharField(max_length=300)),
            ],
        ),
    ]
